export enum QuestionCategory {
  GENERAL_RELATION_STATUS = 'GENERAL_RELATION_STATUS',
  EMOTIONAL_ATTACHMENT = 'EMOTIONAL_ATTACHMENT',
  LOYALTY_AND_TRUST = 'LOYALTY_AND_TRUST',
  ROMANTIC_BEHAVIOR = 'ROMANTIC_BEHAVIOR',
  FUN_AND_DAILY_HABITS = 'FUN_AND_DAILY_HABITS',
}

export enum QuestionCategoryValue {
  GENERAL_RELATION_STATUS = 'GENEL İLİŞKİ DURUMU',
  EMOTIONAL_ATTACHMENT = 'DUYGUSAL BAĞLILIK',
  LOYALTY_AND_TRUST = 'SADAKAT VE GÜVEN',
  ROMANTIC_BEHAVIOR = 'ROMANTİK DAVRANIŞLAR',
  FUN_AND_DAILY_HABITS = 'EĞLENCE VE GÜNLÜK ALIŞKANLIKLAR',
}

export enum AgeRange {
  BETWEEN_14_24 = 'BETWEEN_14_24',
  BETWEEN_25_32 = 'BETWEEN_25_32',
  BETWEEN_33_48 = 'BETWEEN_33_48',
  ABOVE_48 = 'ABOVE_48',
}

export enum RelationDuration {
  NOT_YET = 'NOT_YET',
  ONE_THREE_MONTHS = 'ONE_THREE_MONTHS',
  THREE_TWELVE_MONTHS = 'THREE_TWELVE_MONTHS',
  ONE_YEAR_ABOVE = 'ONE_YEAR_ABOVE',
}

export enum DesiredPartnerFocus {
  EMOTIONAL_SUPPORT = 'EMOTIONAL_SUPPORT',
  ROMANTIC_GESTURE = 'ROMANTIC_GESTURE',
  TIME_SEPARATION = 'TIME_SEPARATION',
  FINANCIAL_SUPPORT = 'FINANCIAL_SUPPORT',
  OTHER = 'OTHER',
}

export enum LoveAspectToAnalyze {
  EMOTIONAL_ATTACHMENT = 'EMOTIONAL_ATTACHMENT',
  LOYALTY = 'LOYALTY',
  ATTENTIVE_BEHAVIOR = 'ATTENTIVE_BEHAVIOR',
}

export enum PerceivedImportance {
  VERY_MUCH = 'VERY_MUCH',
  MODERATE = 'MODERATE',
  UNSURE = 'UNSURE',
}
