export enum QuestionCategory {
  GENERAL_RELATION_STATUS = 'GENERAL_RELATION_STATUS',
  EMOTIONAL_ATTACHMENT = 'EMOTIONAL_ATTACHMENT',
  LOYALTY_AND_TRUST = 'LOYALTY_AND_TRUST',
  ROMANTIC_BEHAVIOR = 'ROMANTIC_BEHAVIOR',
  FUN_AND_DAILY_HABITS = 'FUN_AND_DAILY_HABITS',
}

export enum AgeRange {
  BETWEEN_14_24 = 'BETWEEN_14_24',
  BETWEEN_25_32 = 'BETWEEN_25_32',
  BETWEEN_33_48 = 'BETWEEN_33_48',
  ABOVE_48 = 'ABOVE_48',
}
