export const DummyQuestions = [
  {
    _id: 1,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 2,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 3,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },

  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
  {
    _id: 6,
    turkish: 'Has someone ever written a song for you?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 4,
    turkish: 'Has he ever come to your door on the pretext of seeing you and smiled sweetly?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Not Sure', 'Yes'],
  },
  {
    _id: 5,
    turkish: 'Do you believe in love at first sight?',
    category: 'GENERAL_RELATION_STATUS',
    options: ['No', 'Maybe', 'Yes'],
  },
];
